{% set name = "cloup" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloup-{{ version }}.tar.gz
  sha256: 323f461b37733e49368ab3b68149a9c349c5943a28f992de0d3171da307279ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - click >=8.0,<9.0
    - typing-extensions

test:
  imports:
    - cloup
    - cloup.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janLuke/cloup
  summary: Option groups and subcommand help sections for pallets/click
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
