{% set name = "cloup" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloup-{{ version }}.tar.gz
  sha256: 2ba279ee2544a4ef1c1748731a6698b3d1f5db929357b7123f23d0ba02e27d1e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - click >=7.0,<9.0

test:
  imports:
    - cloup
    - cloup.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janLuke/cloup
  summary: Option groups and subcommand help sections for pallets/click
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
