{% set name = "cloup" %}
{% set version = "3.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloup-{{ version }}.tar.gz
  sha256: c92b261c7bb7e13004930f3fb4b3edad8de2d1f12994dcddbe05bc21990443c5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - click >=8.0,<9.0
    - typing-extensions

test:
  imports:
    - cloup
    - cloup.constraints
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janLuke/cloup
  summary: Option groups and subcommand help sections for pallets/click
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
