{% set name = "cloup" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cloup-{{ version }}.tar.gz
  sha256: b1caa5343d84b2afd18182e1b0b66e764ee5bbdb22e786f8926b23b451384323

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - click >=7.0,<9.0

test:
  imports:
    - cloup
    - cloup.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janLuke/cloup
  summary: Option groups and subcommand help sections for pallets/click
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
