{% set name = "cloup" %}
{% set version = "3.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cloup-{{ version }}.tar.gz
  sha256: 519f524d3c64040e49a0866b5fc0bfd6af3eac0d3d6a4b2b50b33ab0247db2d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools-scm
  run:
    - typing_extensions
    - python >={{ python_min }}
    - click >=8.0,<9.0
    - typing-extensions

test:
  imports:
    - cloup
    - cloup.constraints
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janLuke/cloup
  summary: Option groups and subcommand help sections for pallets/click
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
